export const metadata = { title: "Terms of Service — Analytika" }

export default function TermsPage() {
  return (
    <article>
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> July 2026</p>
      <p>
        These Terms govern your use of Analytika. By creating an account or using the service, you agree to them.
      </p>

      <h2>The service</h2>
      <p>
        Analytika is an AI-assisted data-analysis tool. You upload a dataset and receive statistical analyses,
        charts, and explanations. Results are provided for informational purposes.
      </p>

      <h2>Accounts</h2>
      <p>
        You are responsible for your account credentials and for activity under your account. You must provide
        accurate information and be old enough to form a binding contract in your jurisdiction.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not upload data you don&apos;t have the right to use, or that is unlawful or harmful.</li>
        <li>Do not attempt to disrupt, reverse-engineer, or abuse the service or its rate limits.</li>
        <li>Do not use the service to violate the rights of others.</li>
      </ul>

      <h2>Plans, billing, and refunds</h2>
      <p>
        Paid plans are billed on a recurring basis through our payment provider, Dodo Payments, which acts as the
        merchant of record. Plan limits (such as the number of analyses per month) are shown at signup and may be
        updated with notice. You can cancel at any time; cancellation stops future renewals.
      </p>

      <h2>Your data</h2>
      <p>
        You retain ownership of the data you upload and the results you generate. You grant us the limited license
        needed to process that data to provide the service (including sending it to the processors listed in our
        Privacy Policy).
      </p>

      <h2>No professional advice</h2>
      <p>
        Analytika&apos;s output is generated by automated systems and may contain errors. It is not a substitute for
        professional statistical, financial, medical, legal, or other expert advice. Verify important results before
        relying on them.
      </p>

      <h2>Disclaimers and liability</h2>
      <p>
        The service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, we
        are not liable for indirect or consequential damages, or for decisions made based on the service&apos;s output.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using the service at any time. We may suspend or terminate access for violations of these Terms
        or to protect the service.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these Terms; material changes will be communicated through the service. Continued use after
        changes take effect constitutes acceptance.
      </p>

      <h2>Contact</h2>
      <p>
        Questions? Email <a href="mailto:support@analytika.app">support@analytika.app</a>.
      </p>

      <p style={{ marginTop: 32, fontSize: 12, color: "#9ca3af" }}>
        This document is a starting template and should be reviewed by a qualified professional before you rely on it in production.
      </p>
    </article>
  )
}
